---
# tasks file for users
- name: create user
  user:
    name: user1
    state: present

- name: add public key
  authorized_key:
    user: user1
    state: present
    key: "{{ lookup('file', 'public_key') }}"
